### ISSUE TITLE
Paczki zagraniczne

### ISSUE THREAD

**Issue by lasoczczyk** [t3ko/dpd-pl-api-php#27]
Czesc, udało mi się odpalić. 
Wszystko działa poza paczkami zagranicznymi.
Paczkę tworzy chyba ale problem z etykietą.

`Fatal error: Uncaught TypeError: Return value of T3ko\Dpd\Soap\Types\DocumentGenerationResponseV1::getDocumentData() must be of the type string, null returned in /home/users/nagaz24/public_html/sklep2/admin/dpd-pl-api-php-master/src/Soap/Types/DocumentGenerationResponseV1.php:27 Stack trace: #0 /home/users/nagaz24/public_html/sklep2/admin/dpd-pl-api-php-master/src/Response/GenerateLabelsResponse.php(23): T3ko\Dpd\Soap\Types\DocumentGenerationResponseV1->getDocumentData() #1 /home/users/nagaz24/public_html/sklep2/admin/dpd-pl-api-php-master/src/Api.php(470): T3ko\Dpd\Response\GenerateLabelsResponse::from(Object(T3ko\Dpd\Soap\Types\GenerateSpedLabelsV1Response)) #2 /home/users/nagaz24/public_html/sklep2/admin/dpd-pl-api-php-master/dpd.php(265): T3ko\Dpd\Api->generateLabels(Object(T3ko\Dpd\Request\GenerateLabelsRequest)) #3 {main} thrown in /home/users/nagaz24/public_html/sklep2/admin/dpd-pl-api-php-master/src/Soap/Types/DocumentGenerationResponseV1.php on line 27`

Do Package dodałem:
`$package->addDocumentsInternationalService();`
Błędu nie ma ale wyskoczyło: 
**Usługa 'Dokumenty międzynarodowe' jest dostępna wyłącznie wraz z usługą 'Express'**
Po dodaniu 
`$package->addDpdExpressService();`
Otrzymuję numer paczki ale brak etykiety i mamy identyczny błąd jak powyżej.

Jak prawidłowo przestawić paczkę na tryb International?

**Comment by t3ko** [comment]
Cześć,
"krajowość" etykiet jest na razie zahardkodowana w `GenerateLabelsRequest`.
W ciągu kilku dni będę rozszerzał ten obiekt o nową parametryzację i wtedy pojawi się obsługa paczek zagranicznych.
